/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author esteban
 */
public class Slide1 extends javax.swing.JFrame {
    
    private AFP Capital = new AFP("Capital",0.0453);
    private AFP Cuprum = new AFP("Cuprum",0.0427);
    private AFP Habitad = new AFP("Habitat",0.0447);
    private AFP Modelo = new AFP("Modelo",0.0352);
    private AFP Planvital = new AFP("Planvital",0.0431);
    private AFP Provida = new AFP("Provida",0.0452);

    /**
     * Creates new form Slide1
     */
    public Slide1() {
        initComponents();
        this.setLocationRelativeTo(null);
        Panel1.setVisible(true);
        Panel2.setVisible(false);
        Panel3.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Panel1 = new javax.swing.JPanel();
        AFPCapital = new javax.swing.JButton();
        AFPCuprum = new javax.swing.JButton();
        AFPHabitat = new javax.swing.JButton();
        AFPModelo = new javax.swing.JButton();
        AFPPlanvital = new javax.swing.JButton();
        AFPprovida = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        RentaAFP = new javax.swing.JLabel();
        RetAFP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        FondosAhorrados = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        SueldoPromedio = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FondosP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PensionP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PensionDES = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        RemuAPV = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AFPCapital.setBackground(new java.awt.Color(243, 239, 209));
        AFPCapital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/capital 1.png"))); // NOI18N
        AFPCapital.setToolTipText("");
        AFPCapital.setBorder(null);
        AFPCapital.setBorderPainted(false);
        AFPCapital.setContentAreaFilled(false);
        AFPCapital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AFPCapital.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/capital 2.png"))); // NOI18N
        AFPCapital.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/capital 1.png"))); // NOI18N
        AFPCapital.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/capital 1.png"))); // NOI18N
        AFPCapital.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/capital 2.png"))); // NOI18N
        AFPCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFPCapitalActionPerformed(evt);
            }
        });
        Panel1.add(AFPCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 200));

        AFPCuprum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/cuprum 1.png"))); // NOI18N
        AFPCuprum.setBorder(null);
        AFPCuprum.setBorderPainted(false);
        AFPCuprum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AFPCuprum.setMaximumSize(new java.awt.Dimension(200, 200));
        AFPCuprum.setMinimumSize(new java.awt.Dimension(200, 200));
        AFPCuprum.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/cuprum 2.png"))); // NOI18N
        AFPCuprum.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/cuprum 1.png"))); // NOI18N
        AFPCuprum.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/cuprum 1.png"))); // NOI18N
        AFPCuprum.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/cuprum 2.png"))); // NOI18N
        AFPCuprum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFPCuprumActionPerformed(evt);
            }
        });
        Panel1.add(AFPCuprum, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 200, 200));

        AFPHabitat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/habitad 1.png"))); // NOI18N
        AFPHabitat.setBorder(null);
        AFPHabitat.setBorderPainted(false);
        AFPHabitat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AFPHabitat.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/habitad 2.png"))); // NOI18N
        AFPHabitat.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/habitad 1.png"))); // NOI18N
        AFPHabitat.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/habitad 1.png"))); // NOI18N
        AFPHabitat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/habitad 2.png"))); // NOI18N
        AFPHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFPHabitatActionPerformed(evt);
            }
        });
        Panel1.add(AFPHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, 200));

        AFPModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/modelo 1.png"))); // NOI18N
        AFPModelo.setBorder(null);
        AFPModelo.setBorderPainted(false);
        AFPModelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AFPModelo.setMaximumSize(new java.awt.Dimension(200, 200));
        AFPModelo.setMinimumSize(new java.awt.Dimension(200, 200));
        AFPModelo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/modelo 2.png"))); // NOI18N
        AFPModelo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/modelo 1.png"))); // NOI18N
        AFPModelo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/modelo 1.png"))); // NOI18N
        AFPModelo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/modelo 2.png"))); // NOI18N
        AFPModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFPModeloActionPerformed(evt);
            }
        });
        Panel1.add(AFPModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 200, 200));

        AFPPlanvital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/planvital.png"))); // NOI18N
        AFPPlanvital.setBorder(null);
        AFPPlanvital.setBorderPainted(false);
        AFPPlanvital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AFPPlanvital.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/planvital 2.png"))); // NOI18N
        AFPPlanvital.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/planvital.png"))); // NOI18N
        AFPPlanvital.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/planvital.png"))); // NOI18N
        AFPPlanvital.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/planvital 2.png"))); // NOI18N
        AFPPlanvital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFPPlanvitalActionPerformed(evt);
            }
        });
        Panel1.add(AFPPlanvital, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 200, 200));

        AFPprovida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/provida 1.png"))); // NOI18N
        AFPprovida.setBorder(null);
        AFPprovida.setBorderPainted(false);
        AFPprovida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AFPprovida.setPreferredSize(new java.awt.Dimension(200, 200));
        AFPprovida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/provida 2.png"))); // NOI18N
        AFPprovida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/provida 1.png"))); // NOI18N
        AFPprovida.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/provida 1.png"))); // NOI18N
        AFPprovida.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/provida 2.png"))); // NOI18N
        AFPprovida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFPprovidaActionPerformed(evt);
            }
        });
        Panel1.add(AFPprovida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, 200));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/tops/top1.jpg"))); // NOI18N
        Panel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jLayeredPane1.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        Panel2.setBackground(new java.awt.Color(255, 255, 255));
        Panel2.setMinimumSize(new java.awt.Dimension(600, 730));
        Panel2.setPreferredSize(new java.awt.Dimension(600, 730));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/botones/back.jpg"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, 70));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/botones/next.jpg"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Panel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, 70));

        RentaAFP.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        RentaAFP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Panel2.add(RentaAFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 180, 30));

        RetAFP.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        RetAFP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Panel2.add(RetAFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 180, 30));

        jLabel8.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel8.setText("AFP:");
        Panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 60, 30));

        jLabel19.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel19.setText("Rentabilidad anual:");
        Panel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/tops/top2.2.jpg"))); // NOI18N
        Panel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 600, 50));

        jLabel21.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/tops/top2.1.jpg"))); // NOI18N
        Panel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        Female.setBackground(new java.awt.Color(255, 255, 255));
        Female.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        Female.setText("Mujer");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });

        Male.setBackground(new java.awt.Color(255, 255, 255));
        Male.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        Male.setText("Hombre");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel22.setText("Sexo:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(Male)
                .addGap(61, 61, 61)
                .addComponent(Female))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Female)
                    .addComponent(Male)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 500, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel23.setText("Edad:");

        Edad.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        Edad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Edad.setText("0");
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Panel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 500, 40));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel24.setText("Fondos ahorrados:");

        FondosAhorrados.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        FondosAhorrados.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FondosAhorrados.setText("0");
        FondosAhorrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondosAhorradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FondosAhorrados, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(FondosAhorrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 500, 70));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N

        SueldoPromedio.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        SueldoPromedio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SueldoPromedio.setText("0");
        SueldoPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SueldoPromedioActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel26.setText("Remuneración bruta mensual:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addGap(11, 11, 11)
                .addComponent(SueldoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel25)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SueldoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Panel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 500, 40));

        jLabel27.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("10%");
        Panel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, -1));

        jLabel28.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel28.setText("Cotización obligatoria:");
        Panel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLayeredPane1.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel3.setBackground(new java.awt.Color(255, 255, 255));
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/botones/back.jpg"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Panel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, 70));

        jLabel30.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/tops/top3.2.jpg"))); // NOI18N
        Panel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 600, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        FondosP.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        FondosP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FondosP.setText("FFFF");

        jLabel3.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel3.setText("Fondos:");

        PensionP.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        PensionP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PensionP.setText("pensionsad");

        jLabel5.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel5.setText("Pensión Mensual:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(FondosP, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PensionP, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FondosP)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PensionP)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25))
        );

        Panel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 500, -1));

        jLabel31.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/tops/top3.1.jpg"))); // NOI18N
        Panel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel6.setText("Pensión Deseada:");

        PensionDES.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        PensionDES.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PensionDES.setText("0");
        PensionDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PensionDESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(PensionDES, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PensionDES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        Panel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 500, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPng/botones/calcular.jpg"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10jButton2ActionPerformed(evt);
            }
        });
        Panel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        RemuAPV.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        RemuAPV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Work Sans", 0, 24)); // NOI18N
        jLabel9.setText("Remuneración mensual destinada al APV");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(RemuAPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemuAPV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 500, -1));

        jLayeredPane1.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 730));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 600, 730));

        jPanel1.setBackground(new java.awt.Color(31, 60, 152));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 600, 80));

        jPanel3.setBackground(new java.awt.Color(76, 112, 232));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(76, 112, 232));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Retirement Simulator");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void SueldoPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SueldoPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SueldoPromedioActionPerformed

    private void FondosAhorradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondosAhorradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FondosAhorradosActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
        if (Male.isSelected()){
            Female.setSelected(false);
            main.edadJ=65;
            main.CP=276;
            System.out.println(main.edadJ);
        }
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
        if (Female.isSelected()){
            Male.setSelected(false);
            main.edadJ=60;
            main.CP=276;
            System.out.println(main.edadJ);
        }
    }//GEN-LAST:event_FemaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        main.edadT=Integer.parseInt(Edad.getText());
        main.SueldoA=Integer.parseInt(SueldoPromedio.getText());
        main.FondosA=Integer.parseInt(FondosAhorrados.getText());
        Panel3.setVisible(true);
        Panel2.setVisible(false);
        FondosP.setText("$"+String.format("%.0f", main.Fondo_Futuro()));
        PensionP.setText("$"+String.format("%.0f", main.Fondo_Futuro()/main.CP));
        //System.out.println(main.Fondo_Futuro());

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Panel1.setVisible(true);
        Panel2.setVisible(false);
        RetAFP.setText(main.mainAFP.getNombre());
        RentaAFP.setText(main.mainAFP.getRenta()*100 + "%");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AFPprovidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFPprovidaActionPerformed
        // TODO add your handling code here:
        //System.out.println(Provida.Info());
        main.mainAFP=this.Provida;
        Panel1.setVisible(false);
        Panel2.setVisible(true);
        RetAFP.setText(main.mainAFP.getNombre());
        RentaAFP.setText(String.format("%.2f", main.mainAFP.getRenta()*100) + "%");
    }//GEN-LAST:event_AFPprovidaActionPerformed

    private void AFPPlanvitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFPPlanvitalActionPerformed
        // TODO add your handling code here:
        main.mainAFP=this.Planvital;
        Panel1.setVisible(false);
        Panel2.setVisible(true);
        RetAFP.setText(main.mainAFP.getNombre());
        RentaAFP.setText(String.format("%.2f", main.mainAFP.getRenta()*100) + "%");
    }//GEN-LAST:event_AFPPlanvitalActionPerformed

    private void AFPModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFPModeloActionPerformed
        // TODO add your handling code here:
        main.mainAFP=this.Modelo;
        Panel1.setVisible(false);
        Panel2.setVisible(true);
        RetAFP.setText(main.mainAFP.getNombre());
        RentaAFP.setText(String.format("%.2f", main.mainAFP.getRenta()*100) + "%");
    }//GEN-LAST:event_AFPModeloActionPerformed

    private void AFPHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFPHabitatActionPerformed
        // TODO add your handling code here:
        main.mainAFP=this.Habitad;
        Panel1.setVisible(false);
        Panel2.setVisible(true);
        RetAFP.setText(main.mainAFP.getNombre());
        RentaAFP.setText(String.format("%.2f", main.mainAFP.getRenta()*100) + "%");
    }//GEN-LAST:event_AFPHabitatActionPerformed

    private void AFPCuprumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFPCuprumActionPerformed
        // TODO add your handling code here:
        //System.out.println(Cuprum.Info());
        //main.setAFP(this.Capital);
        main.mainAFP=this.Cuprum;
        Panel1.setVisible(false);
        Panel2.setVisible(true);
        RetAFP.setText(main.mainAFP.getNombre());
        RentaAFP.setText(String.format("%.2f", main.mainAFP.getRenta()*100) + "%");
        //System.out.println("cuprum is main");
    }//GEN-LAST:event_AFPCuprumActionPerformed

    private void AFPCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFPCapitalActionPerformed
        // TODO add your handling code here:
        //System.out.println(Capital.Info());
        main.mainAFP=this.Capital;
        Panel1.setVisible(false);
        Panel2.setVisible(true);
        RetAFP.setText(main.mainAFP.getNombre());
        RentaAFP.setText(String.format("%.2f", main.mainAFP.getRenta()*100) + "%");

    }//GEN-LAST:event_AFPCapitalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Panel3.setVisible(false);
        Panel2.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PensionDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PensionDESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PensionDESActionPerformed

    private void jButton10jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10jButton2ActionPerformed
        // TODO add your handling code here:
        main.Deseado=Integer.parseInt(PensionDES.getText());
        if(main.APV()<0){
            RemuAPV.setText("Ingrese un valor valido");
        }else{
            RemuAPV.setText("$"+String.format("%.0f", main.APV()));
        }
        
    }//GEN-LAST:event_jButton10jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slide1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AFPCapital;
    private javax.swing.JButton AFPCuprum;
    private javax.swing.JButton AFPHabitat;
    private javax.swing.JButton AFPModelo;
    private javax.swing.JButton AFPPlanvital;
    private javax.swing.JButton AFPprovida;
    private javax.swing.JTextField Edad;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField FondosAhorrados;
    private javax.swing.JLabel FondosP;
    private javax.swing.JRadioButton Male;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JTextField PensionDES;
    private javax.swing.JLabel PensionP;
    private javax.swing.JLabel RemuAPV;
    private javax.swing.JLabel RentaAFP;
    private javax.swing.JLabel RetAFP;
    private javax.swing.JTextField SueldoPromedio;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
